from datetime import date


CURRENT_DATE = date(2026, 8, 10)


DEALS = [
    {
        "id": "deal_201",
        "company": "Acme Corporation",
        "deal_name": "Enterprise Platform Expansion",
        "amount": 210000,
        "stage": "Proposal",
        "risk_level": "High",
        "risk_score": 82,
        "rep_name": "Maya Lin",
        "last_activity_date": date(2026, 8, 10),
        "last_activity_label": "2 hours ago",
        "next_step": "Executive review",
        "expected_close_date": date(2026, 8, 28),
        "ai_signal": "Stakeholder coverage is incomplete",
    },
    {
        "id": "deal_202",
        "company": "TechNova",
        "deal_name": "AI Analytics Rollout",
        "amount": 180000,
        "stage": "Negotiation",
        "risk_level": "Medium",
        "risk_score": 58,
        "rep_name": "Alex Rivera",
        "last_activity_date": date(2026, 8, 10),
        "last_activity_label": "Today",
        "next_step": "Legal redlines",
        "expected_close_date": date(2026, 8, 15),
        "ai_signal": "Strong engagement, procurement pending",
    },
    {
        "id": "deal_203",
        "company": "Vertex Systems",
        "deal_name": "Security Operations Suite",
        "amount": 275000,
        "stage": "Qualification",
        "risk_level": "Low",
        "risk_score": 24,
        "rep_name": "Maya Lin",
        "last_activity_date": date(2026, 8, 9),
        "last_activity_label": "1 day ago",
        "next_step": "Security workshop",
        "expected_close_date": date(2026, 9, 5),
        "ai_signal": "Multi-threaded early with clear champions",
    },
    {
        "id": "deal_204",
        "company": "Northstar Labs",
        "deal_name": "Data Warehouse Modernization",
        "amount": 96000,
        "stage": "Discovery",
        "risk_level": "Medium",
        "risk_score": 46,
        "rep_name": "Jordan Smith",
        "last_activity_date": date(2026, 8, 7),
        "last_activity_label": "3 days ago",
        "next_step": "Discovery call",
        "expected_close_date": date(2026, 9, 8),
        "ai_signal": "Discovery is thin and budget is unconfirmed",
    },
    {
        "id": "deal_205",
        "company": "Pioneer Financial",
        "deal_name": "Compliance Automation",
        "amount": 300000,
        "stage": "Contract",
        "risk_level": "High",
        "risk_score": 77,
        "rep_name": "Alex Rivera",
        "last_activity_date": date(2026, 8, 10),
        "last_activity_label": "4 hours ago",
        "next_step": "Final signature",
        "expected_close_date": date(2026, 8, 13),
        "ai_signal": "Legal stalled after redline review",
    },
    {
        "id": "deal_206",
        "company": "CloudAxis",
        "deal_name": "Revenue Intelligence Platform",
        "amount": 205000,
        "stage": "Proposal",
        "risk_level": "Medium",
        "risk_score": 55,
        "rep_name": "Maya Lin",
        "last_activity_date": date(2026, 8, 9),
        "last_activity_label": "Yesterday",
        "next_step": "Proposal review",
        "expected_close_date": date(2026, 9, 1),
        "ai_signal": "Follow-up cadence is solid but urgency is soft",
    },
    {
        "id": "deal_207",
        "company": "Brightline Health",
        "deal_name": "Patient Engagement Platform",
        "amount": 240000,
        "stage": "Closed Won",
        "risk_level": "Low",
        "risk_score": 18,
        "rep_name": "Alex Rivera",
        "last_activity_date": date(2026, 8, 8),
        "last_activity_label": "2 days ago",
        "next_step": "Kickoff onboarding",
        "expected_close_date": date(2026, 8, 9),
        "ai_signal": "Strong executive alignment converted quickly",
    },
    {
        "id": "deal_208",
        "company": "Apex Manufacturing",
        "deal_name": "Factory Visibility Program",
        "amount": 220000,
        "stage": "Qualification",
        "risk_level": "Medium",
        "risk_score": 49,
        "rep_name": "Jordan Smith",
        "last_activity_date": date(2026, 8, 5),
        "last_activity_label": "5 days ago",
        "next_step": "Plant operations workshop",
        "expected_close_date": date(2026, 9, 12),
        "ai_signal": "Operational sponsor engaged, finance not yet involved",
    },
    {
        "id": "deal_209",
        "company": "NovaWorks",
        "deal_name": "Workflow Automation Suite",
        "amount": 190000,
        "stage": "Negotiation",
        "risk_level": "High",
        "risk_score": 80,
        "rep_name": "Maya Lin",
        "last_activity_date": date(2026, 8, 10),
        "last_activity_label": "6 hours ago",
        "next_step": "Procurement check-in",
        "expected_close_date": date(2026, 8, 24),
        "ai_signal": "Single-threaded opportunity with delayed follow-up",
    },
    {
        "id": "deal_210",
        "company": "Summit Retail",
        "deal_name": "Forecasting & Planning Hub",
        "amount": 150000,
        "stage": "Discovery",
        "risk_level": "Low",
        "risk_score": 31,
        "rep_name": "Alex Rivera",
        "last_activity_date": date(2026, 8, 10),
        "last_activity_label": "Today",
        "next_step": "Multi-stakeholder discovery",
        "expected_close_date": date(2026, 9, 18),
        "ai_signal": "High engagement momentum in early discovery",
    },
    {
        "id": "deal_211",
        "company": "Orbit Systems",
        "deal_name": "Network Resilience Upgrade",
        "amount": 175000,
        "stage": "Closed Lost",
        "risk_level": "High",
        "risk_score": 88,
        "rep_name": "Jordan Smith",
        "last_activity_date": date(2026, 8, 3),
        "last_activity_label": "1 week ago",
        "next_step": "Post-mortem review",
        "expected_close_date": date(2026, 8, 6),
        "ai_signal": "No confirmed next step before budget freeze",
    },
    {
        "id": "deal_212",
        "company": "BluePeak",
        "deal_name": "Customer Success Intelligence",
        "amount": 200000,
        "stage": "Proposal",
        "risk_level": "Medium",
        "risk_score": 52,
        "rep_name": "Maya Lin",
        "last_activity_date": date(2026, 8, 9),
        "last_activity_label": "Yesterday",
        "next_step": "Success plan review",
        "expected_close_date": date(2026, 9, 3),
        "ai_signal": "Consistent follow-up cadence with growing champion support",
    },
    {
        "id": "deal_213",
        "company": "Meridian Health",
        "deal_name": "Care Coordination Platform",
        "amount": 240000,
        "stage": "Discovery",
        "risk_level": "Low",
        "risk_score": 28,
        "rep_name": "Alex Rivera",
        "last_activity_date": date(2026, 8, 10),
        "last_activity_label": "3 hours ago",
        "next_step": "Technical deep dive",
        "expected_close_date": date(2026, 9, 22),
        "ai_signal": "Decision maker is engaged early",
    },
    {
        "id": "deal_214",
        "company": "Harbor Energy",
        "deal_name": "Field Service Analytics",
        "amount": 120000,
        "stage": "Contract",
        "risk_level": "Medium",
        "risk_score": 60,
        "rep_name": "Jordan Smith",
        "last_activity_date": date(2026, 8, 10),
        "last_activity_label": "5 hours ago",
        "next_step": "Security questionnaire",
        "expected_close_date": date(2026, 8, 16),
        "ai_signal": "Contract has momentum but security review is a risk",
    },
]
