"""
Mock Data Module for Sales Behavior Intelligence Platform.
Contains realistic test data matching the problem statement personas (Maya, David, Priya).
"""

MOCK_REPS = [
    {
        "id": "rep_1",
        "name": "Maya Lin",
        "role": "Enterprise AE",
        "deals_count": 6,
        "quota_attainment": 82,
    },
    {
        "id": "rep_2",
        "name": "Alex Rivera",
        "role": "Senior AE",
        "deals_count": 8,
        "quota_attainment": 94,
    },
    {
        "id": "rep_3",
        "name": "Jordan Smith",
        "role": "Mid-Market AE",
        "deals_count": 5,
        "quota_attainment": 68,
    },
]

MOCK_DEALS = [
    {
        "id": "deal_101",
        "name": "Acme Corp — Enterprise Platform License",
        "company": "Acme Corp",
        "amount": 145000,
        "stage": "Proposal Sent",
        "rep_id": "rep_1",
        "rep_name": "Maya Lin",
        "risk_level": "High",
        "risk_score": 78,
        "days_in_stage": 18,
        "last_activity": "2026-07-30 (4 days ago)",
        "top_flag": "Slow Post-Demo Follow-Up & Single Threaded",
        "primary_contact": "Sarah Jenkins (VP Engineering)",
    },
    {
        "id": "deal_102",
        "name": "Apex Logistics — Cloud Migration",
        "company": "Apex Logistics",
        "amount": 92000,
        "stage": "Discovery",
        "rep_id": "rep_1",
        "rep_name": "Maya Lin",
        "risk_level": "Medium",
        "risk_score": 52,
        "days_in_stage": 9,
        "last_activity": "2026-08-01 (2 days ago)",
        "top_flag": "Thin Discovery / Missing Next Steps",
        "primary_contact": "Marcus Vance (Director of IT)",
    },
    {
        "id": "deal_103",
        "name": "Starlight Media — Annual Subscription",
        "company": "Starlight Media",
        "amount": 210000,
        "stage": "Negotiation / Legal",
        "rep_id": "rep_2",
        "rep_name": "Alex Rivera",
        "risk_level": "Low",
        "risk_score": 15,
        "days_in_stage": 4,
        "last_activity": "2026-08-03 (Today)",
        "top_flag": "Healthy Momentum",
        "primary_contact": "Elena Rostova (CFO)",
    },
    {
        "id": "deal_104",
        "name": "Nexus Technologies — Data Intelligence",
        "company": "Nexus Technologies",
        "amount": 65000,
        "stage": "Demo Completed",
        "rep_id": "rep_3",
        "rep_name": "Jordan Smith",
        "risk_level": "High",
        "risk_score": 85,
        "days_in_stage": 24,
        "last_activity": "2026-07-22 (12 days ago)",
        "top_flag": "No Follow-Up > 10 Days & No Next Step",
        "primary_contact": "David Chen (Head of Ops)",
    },
    {
        "id": "deal_105",
        "name": "Vortex Systems — Security Suite",
        "company": "Vortex Systems",
        "amount": 175000,
        "stage": "Solution Validation",
        "rep_id": "rep_2",
        "rep_name": "Alex Rivera",
        "risk_level": "Medium",
        "risk_score": 45,
        "days_in_stage": 11,
        "last_activity": "2026-08-02 (1 day ago)",
        "top_flag": "Unclear Economic Buyer Engagement",
        "primary_contact": "Rachel Green (CISO)",
    },
]

MOCK_TIMELINES = {
    "deal_101": [
        {
            "id": "ev_1",
            "date": "2026-07-10",
            "type": "CRM Event",
            "title": "Stage Moved to Initial Discovery",
            "details": "Rep created opportunity after inbound demo request.",
            "icon": "📌",
            "flag": None,
        },
        {
            "id": "ev_2",
            "date": "2026-07-12",
            "type": "Call Transcript",
            "title": "Discovery & Technical Requirements Call (45 mins)",
            "details": "Discussed scalability needs with Sarah Jenkins. Security questions raised.",
            "icon": "📞",
            "flag": "Good Technical Coverage",
        },
        {
            "id": "ev_3",
            "date": "2026-07-14",
            "type": "Call Transcript",
            "title": "Product Demo Call with Tech Team",
            "details": "Demo went well. Client asked for custom pricing quote by end of week.",
            "icon": "🎥",
            "flag": None,
        },
        {
            "id": "ev_4",
            "date": "2026-07-18",
            "type": "Email",
            "title": "Proposal Sent to Buyer",
            "details": "Sent proposal PDF 96 hours after demo call.",
            "icon": "✉️",
            "flag": "Slow Follow-Up (96h delay post-demo)",
        },
        {
            "id": "ev_5",
            "date": "2026-07-25",
            "type": "CRM Event",
            "title": "Stage Advanced to Proposal Sent",
            "details": "No response received yet from procurement or CFO.",
            "icon": "⏳",
            "flag": "Single-Threaded (Only 1 stakeholder engaged)",
        },
        {
            "id": "ev_6",
            "date": "2026-07-30",
            "type": "Email",
            "title": "Follow-up check-in sent to Sarah Jenkins",
            "details": "'Hi Sarah, checking in on the proposal.' No calendar meeting attached.",
            "icon": "✉️",
            "flag": "Weak Next Step / Passive Follow-Up",
        },
    ],
    "deal_102": [
        {
            "id": "ev_10",
            "date": "2026-07-25",
            "type": "CRM Event",
            "title": "Inbound Lead Qualified",
            "details": "Lead assigned to Maya Lin.",
            "icon": "📌",
            "flag": None,
        },
        {
            "id": "ev_11",
            "date": "2026-08-01",
            "type": "Call Transcript",
            "title": "First Intro Call (20 mins)",
            "details": "Short call. Covered high level goals. Rep promised pricing draft next.",
            "icon": "📞",
            "flag": "Thin Discovery (Skipped pain & budget questions)",
        },
    ],
    "deal_103": [
        {
            "id": "ev_20",
            "date": "2026-07-05",
            "type": "CRM Event",
            "title": "Opportunity Qualified",
            "details": "Multi-year deal identified.",
            "icon": "📌",
            "flag": None,
        },
        {
            "id": "ev_21",
            "date": "2026-07-15",
            "type": "Call Transcript",
            "title": "Executive Alignment Call",
            "details": "Engaged CFO, VP Ops, and Legal lead in call.",
            "icon": "🤝",
            "flag": "Multi-Threaded Champion Building",
        },
        {
            "id": "ev_22",
            "date": "2026-08-03",
            "type": "Email",
            "title": "Legal Redlines Approved",
            "details": "Contract ready for signature.",
            "icon": "✅",
            "flag": "Strong Momentum",
        },
    ],
}

MOCK_COACHING_CARDS = {
    "deal_101": [
        {
            "id": "card_1",
            "flag_title": "Slow Post-Demo Proposal Follow-Up",
            "severity": "High Risk",
            "evidence": "Demo call took place on July 14th, but proposal email was sent on July 18th (96 hours lag). Historical data shows deals with >48h proposal lag have 40% lower win rate.",
            "impact": "Buyer momentum cooled down; no follow-up meeting was pre-booked during the demo.",
            "action": "Coach Maya to book a explicit 'Proposal Review Call' on the calendar before ending the demo call.",
            "status": "Needs Coaching",
        },
        {
            "id": "card_2",
            "flag_title": "Single-Threaded Stakeholder Engagement",
            "severity": "High Risk",
            "evidence": "Only 1 contact (Sarah Jenkins - VP Eng) has been engaged across 3 emails and 2 calls. No interaction logged with CFO or Procurement.",
            "impact": "High risk of approval delay or silent rejection during executive review.",
            "action": "Guide Maya to request an executive introduction: 'Who else on the leadership team will evaluate the ROI before signing?'",
            "status": "Needs Coaching",
        },
        {
            "id": "card_3",
            "flag_title": "Passive Follow-Up Email Language",
            "severity": "Medium Risk",
            "evidence": "Email on July 30th used passive phrasing: 'Just checking in if you had a chance to look.' No specific agenda or value hook proposed.",
            "impact": "Low response probability (<15% for generic check-ins).",
            "action": "Share response template focusing on business trigger: 'Sarah, shared a relevant case study on how X company solved latency during migration...'",
            "status": "Suggested Playbook",
        },
    ],
    "deal_102": [
        {
            "id": "card_4",
            "flag_title": "Thin Discovery Call Execution",
            "severity": "Medium Risk",
            "evidence": "Transcript analysis of Aug 1 call shows rep spoke 72% of the time. Budget and decision timeline questions were not asked.",
            "impact": "Moving to solution proposal without clear ROI anchor.",
            "action": "Run a 15-minute 1:1 session with Maya on open-ended discovery frameworks (SPICED / MEDDPICC).",
            "status": "Needs Coaching",
        }
    ],
}
